name = "generic_ecs"
description = "A generic ECS for Ada language inspired by Entt"
version = "0.6.0-dev"

authors = ["louis-etne"]
maintainers = ["louis-etne@mail.com"]
maintainers-logins = ["louis-etne"]
